"""Added error to image & profile_storage_key for user

Revision ID: 2cc6f83a801f
Revises: ec67c2dbbfd5
Create Date: 2025-06-10 17:23:41.703740

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cc6f83a801f"
down_revision: Union[str, None] = "ec67c2dbbfd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("error", sa.String(length=2048), nullable=True))
    op.drop_constraint(
        op.f("projects_collection_id_fkey"), "projects", type_="foreignkey"
    )
    op.drop_column("projects", "collection_id")
    op.add_column(
        "users",
        sa.Column("profile_image_storage_key", sa.String(length=1024), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image_storage_key")
    op.add_column(
        "projects",
        sa.Column(
            "collection_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("projects_collection_id_fkey"),
        "projects",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_column("images", "error")
    # ### end Alembic commands ###
