"""rename metadata->assets

Revision ID: 34ed37849c3b
Revises: a5c67087b7fa
Create Date: 2025-07-11 16:56:05.364955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34ed37849c3b'
down_revision: Union[str, None] = 'a5c67087b7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('styleboards', sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('styleboards', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('styleboards', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('styleboards', 'assets')
    # ### end Alembic commands ###
