"""added mesh, multiview to image, and more

Revision ID: 4111d96afe4e
Revises: 8a2825ec31b5
Create Date: 2025-05-17 15:09:44.882016

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4111d96afe4e"
down_revision: Union[str, None] = "8a2825ec31b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meshes",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("image_id", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("octree_resolution", sa.String(length=8), nullable=False),
        sa.Column("num_inference_steps", sa.Integer(), nullable=False),
        sa.Column("face_count", sa.Integer(), nullable=False),
        sa.Column("texture", sa.Boolean(), nullable=False),
        sa.Column("guidance_scale", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "images",
        sa.Column("multiview_image_dir", sa.String(length=1024), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "multiview_image_dir")
    op.drop_table("meshes")
    # ### end Alembic commands ###
