"""added google auth column for users

Revision ID: 7130863fdf95
Revises: b92945d0dda0
Create Date: 2025-07-09 11:24:15.697424

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7130863fdf95"
down_revision: Union[str, None] = "b92945d0dda0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("google_auth_id", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "google_auth_id")
    # ### end Alembic commands ###
