"""Added external_id to Image for multiturn editing

Revision ID: 73ea39eb422f
Revises: bd0a9b055466
Create Date: 2025-05-30 15:13:03.236198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ea39eb422f'
down_revision: Union[str, None] = 'bd0a9b055466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('external_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'external_id')
    # ### end Alembic commands ###
