"""edits to accomodate multiple meshes/textures for a project version

Revision ID: 74a86ec14f3d
Revises: 84237228dc30
Create Date: 2025-06-19 12:32:52.696367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from donna_common.orm.base import asset_stage_enum


# revision identifiers, used by Alembic.
revision: str = '74a86ec14f3d'
down_revision: Union[str, None] = '84237228dc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_version_assets',
    sa.Column('project_version_id', sa.String(length=128), nullable=False),
    sa.Column('asset_type', asset_stage_enum, nullable=False),
    sa.Column('asset_id', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_version_id', 'asset_type', 'asset_id', name='pk_project_version_asset')
    )
    op.add_column('credit_transactions', sa.Column('action_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'credit_transactions', 'project_actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_branches', 'head_version_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_versions', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('project_versions_mesh_id_fkey', 'project_versions', type_='foreignkey')
    op.drop_constraint('project_versions_texture_id_fkey', 'project_versions', type_='foreignkey')
    op.drop_constraint('project_versions_image_id_fkey', 'project_versions', type_='foreignkey')
    op.create_foreign_key(None, 'project_versions', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_versions', 'image_id')
    op.drop_column('project_versions', 'texture_id')
    op.drop_column('project_versions', 'mesh_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_versions', sa.Column('mesh_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('project_versions', sa.Column('texture_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('project_versions', sa.Column('image_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_versions', type_='foreignkey')
    op.create_foreign_key('project_versions_image_id_fkey', 'project_versions', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('project_versions_texture_id_fkey', 'project_versions', 'textures', ['texture_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('project_versions_mesh_id_fkey', 'project_versions', 'meshes', ['mesh_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_versions', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_branches', 'head_version_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.drop_column('credit_transactions', 'action_id')
    op.drop_table('project_version_assets')
    # ### end Alembic commands ###
