"""Added active for all models & public for projects

Revision ID: 773797b6c838
Revises: 7e4553b37827
Create Date: 2025-06-03 11:25:28.680747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773797b6c838'
down_revision: Union[str, None] = '7e4553b37827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('images', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('meshes', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('projects', sa.Column('public', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('projects', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('textures', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.drop_column('textures', 'active')
    op.drop_column('projects', 'active')
    op.drop_column('projects', 'public')
    op.drop_column('meshes', 'active')
    op.drop_column('images', 'active')
    op.drop_column('credit_transactions', 'active')
    # ### end Alembic commands ###
