"""added notifs and light_mode to user

Revision ID: 7e4553b37827
Revises: 73ea39eb422f
Create Date: 2025-05-31 18:46:17.317731

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e4553b37827"
down_revision: Union[str, None] = "73ea39eb422f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "notification_low_credits",
            sa.Boolean(),
            server_default="True",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "notification_monthly_credits",
            sa.Boolean(),
            server_default="True",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "notification_product_updates",
            sa.Boolean(),
            server_default="True",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "notification_promotions",
            sa.Boolean(),
            server_default="True",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("light_mode", sa.Boolean(), server_default="True", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "light_mode")
    op.drop_column("users", "notification_promotions")
    op.drop_column("users", "notification_product_updates")
    op.drop_column("users", "notification_monthly_credits")
    op.drop_column("users", "notification_low_credits")
    # ### end Alembic commands ###
