"""Versioning tables

Revision ID: 84237228dc30
Revises: cc9f2cfa2af8
Create Date: 2025-06-18 23:13:34.530617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from donna_common.orm.base import asset_stage_enum

# revision identifiers, used by Alembic.
revision: str = '84237228dc30'
down_revision: Union[str, None] = 'cc9f2cfa2af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_versions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('parent_version_id', sa.String(length=128), nullable=True),
    sa.Column('image_id', sa.String(length=128), nullable=True),
    sa.Column('mesh_id', sa.String(length=128), nullable=True),
    sa.Column('texture_id', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mesh_id'], ['meshes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['texture_id'], ['textures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_actions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_version_id', sa.String(length=128), nullable=False),
    sa.Column('asset_stage', asset_stage_enum, nullable=False),
    sa.Column('asset_id', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_branches',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('head_version_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['head_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('images', 'original_image_id', new_column_name="parent_image_id")
    op.create_foreign_key(None, 'images', 'images', ['parent_image_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('meshes', sa.Column('parent_mesh_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'meshes', 'meshes', ['parent_mesh_id'], ['id'], ondelete='CASCADE')
    op.add_column('textures', sa.Column('parent_texture_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'textures', 'textures', ['parent_texture_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('textures_parent_texture_id_fkey', 'textures', type_='foreignkey')
    op.drop_column('textures', 'parent_texture_id')
    op.drop_constraint('meshes_parent_mesh_id_fkey', 'meshes', type_='foreignkey')
    op.drop_column('meshes', 'parent_mesh_id')
    op.alter_column('images', 'parent_image_id', new_column_name="original_image_id")
    op.drop_constraint('images_parent_image_id_fkey', 'images', type_='foreignkey')
    op.drop_table('project_branches')
    op.drop_table('project_actions')
    op.drop_table('project_versions')
    # ### end Alembic commands ###
