"""change og_img_url to nullable

Revision ID: 8a2825ec31b5
Revises: 1ba35c902c95
Create Date: 2025-05-06 07:10:44.839946

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a2825ec31b5"
down_revision: Union[str, None] = "1ba35c902c95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "images",
        "original_image_url",
        existing_type=sa.VARCHAR(length=1024),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "images",
        "original_image_url",
        existing_type=sa.VARCHAR(length=1024),
        nullable=False,
    )
    # ### end Alembic commands ###
