"""added latents_storage_key to mesh

Revision ID: 8b2c4ec6b18d
Revises: 74a86ec14f3d
Create Date: 2025-06-19 19:22:26.070486

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b2c4ec6b18d"
down_revision: Union[str, None] = "74a86ec14f3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meshes",
        sa.Column("latents_storage_key", sa.String(length=1024), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meshes", "latents_storage_key")
    # ### end Alembic commands ###
