"""added texture & modified mesh to match runpod

Revision ID: 96557596f5d5
Revises: dba8fc0f2a49
Create Date: 2025-05-23 00:26:39.418002

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96557596f5d5"
down_revision: Union[str, None] = "dba8fc0f2a49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "textures",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("image_id", sa.String(length=128), nullable=False),
        sa.Column("mesh_id", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("prompt", sa.String(length=1024), nullable=True),
        sa.Column("n_inference_steps", sa.Integer(), nullable=False),
        sa.Column("guidance_scale", sa.Float(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("lora_scale", sa.Float(), nullable=False),
        sa.Column("reference_conditioning_scale", sa.Float(), nullable=False),
        sa.Column("gpu_provider_response", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mesh_id"],
            ["meshes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "meshes",
        sa.Column(
            "mc_level", sa.Float(), nullable=False, server_default=sa.text("0.0")
        ),
    )
    op.execute("UPDATE meshes SET mc_level = 0.0 WHERE mc_level IS NULL;")
    op.add_column("meshes", sa.Column("label", sa.String(length=512), nullable=True))
    op.add_column("meshes", sa.Column("caption", sa.String(length=1024), nullable=True))
    op.drop_column("meshes", "texture")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meshes", sa.Column("texture", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_column("meshes", "caption")
    op.drop_column("meshes", "label")
    op.drop_column("meshes", "mc_level")
    op.drop_table("textures")
    # ### end Alembic commands ###
