"""added thumbnail key to Image

Revision ID: a718b87d7a9d
Revises: 2cc6f83a801f
Create Date: 2025-06-11 21:04:36.425119

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a718b87d7a9d"
down_revision: Union[str, None] = "2cc6f83a801f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column("thumbnail_image_storage_key", sa.String(length=1024), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "thumbnail_image_storage_key")
    # ### end Alembic commands ###
