"""autodelete

Revision ID: af698cce6925
Revises: 8b2c4ec6b18d
Create Date: 2025-06-24 13:56:24.612504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af698cce6925'
down_revision: Union[str, None] = '8b2c4ec6b18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credit_transactions_action_id_fkey', 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'credit_transactions', 'project_actions', ['action_id'], ['id'])
    op.drop_constraint('project_branches_head_version_id_fkey', 'project_branches', type_='foreignkey')
    op.create_foreign_key(None, 'project_branches', 'project_versions', ['head_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_branches', type_='foreignkey')
    op.create_foreign_key('project_branches_head_version_id_fkey', 'project_branches', 'project_versions', ['head_version_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.create_foreign_key('credit_transactions_action_id_fkey', 'credit_transactions', 'project_actions', ['action_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
