"""edit user to use stripe fields

Revision ID: b92945d0dda0
Revises: af698cce6925
Create Date: 2025-07-05 20:29:28.159439

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b92945d0dda0"
down_revision: Union[str, None] = "af698cce6925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "subscription_id", sa.String(length=128), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "users", sa.Column("stripe_customer_id", sa.String(length=128), nullable=True)
    )
    op.drop_column("users", "subscription_tier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "subscription_tier",
            sa.VARCHAR(length=32),
            server_default=sa.text("'free'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "subscription_id")
    # ### end Alembic commands ###
