"""Changed mesh & texture fields to be nullable

Revision ID: cc9f2cfa2af8
Revises: a718b87d7a9d
Create Date: 2025-06-16 11:41:39.596323

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc9f2cfa2af8"
down_revision: Union[str, None] = "a718b87d7a9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "images",
        "prompt",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=4096),
        existing_nullable=False,
    )
    op.alter_column(
        "meshes", "octree_resolution", existing_type=sa.VARCHAR(length=8), nullable=True
    )
    op.alter_column(
        "meshes", "num_inference_steps", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "meshes",
        "guidance_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "meshes",
        "mc_level",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("0.0"),
    )
    op.drop_constraint("meshes_image_id_fkey", "meshes", type_="foreignkey")
    op.create_foreign_key(
        None, "meshes", "images", ["image_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "textures", "n_inference_steps", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "textures",
        "guidance_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "textures",
        "lora_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "textures",
        "reference_conditioning_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_constraint("textures_image_id_fkey", "textures", type_="foreignkey")
    op.drop_constraint("textures_mesh_id_fkey", "textures", type_="foreignkey")
    op.create_foreign_key(
        None, "textures", "meshes", ["mesh_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "textures", "images", ["image_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "textures", type_="foreignkey")
    op.drop_constraint(None, "textures", type_="foreignkey")
    op.create_foreign_key(
        "textures_mesh_id_fkey", "textures", "meshes", ["mesh_id"], ["id"]
    )
    op.create_foreign_key(
        "textures_image_id_fkey", "textures", "images", ["image_id"], ["id"]
    )
    op.alter_column(
        "textures",
        "reference_conditioning_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "textures",
        "lora_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "textures",
        "guidance_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "textures", "n_inference_steps", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(None, "meshes", type_="foreignkey")
    op.create_foreign_key(
        "meshes_image_id_fkey", "meshes", "images", ["image_id"], ["id"]
    )
    op.alter_column(
        "meshes",
        "mc_level",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("0.0"),
    )
    op.alter_column(
        "meshes",
        "guidance_scale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "meshes", "num_inference_steps", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "meshes",
        "octree_resolution",
        existing_type=sa.VARCHAR(length=8),
        nullable=False,
    )
    op.alter_column(
        "images",
        "prompt",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
