"""og_image_url->og_image_id

Revision ID: dba8fc0f2a49
Revises: ec25d80db35e
Create Date: 2025-05-18 21:10:52.905641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba8fc0f2a49'
down_revision: Union[str, None] = 'ec25d80db35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('original_image_id', sa.String(length=128), nullable=True))
    op.drop_column('images', 'original_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('original_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('images', 'original_image_id')
    # ### end Alembic commands ###
