"""added render-pic column and format-storage-keys JSONB column for meshes & textures

Revision ID: e1986b7b83cc
Revises: fd87b8bab1cd
Create Date: 2025-06-04 15:49:52.855331

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1986b7b83cc"
down_revision: Union[str, None] = "fd87b8bab1cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meshes",
        sa.Column("static_render_storage_key", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "meshes",
        sa.Column(
            "format_storage_keys",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "textures",
        sa.Column("static_render_storage_key", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "textures",
        sa.Column(
            "format_storage_keys",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("textures", "format_storage_keys")
    op.drop_column("textures", "static_render_storage_key")
    op.drop_column("meshes", "format_storage_keys")
    op.drop_column("meshes", "static_render_storage_key")
    # ### end Alembic commands ###
