"""changed urls to storage_keys

Revision ID: ec25d80db35e
Revises: 4111d96afe4e
Create Date: 2025-05-18 21:04:16.436647

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec25d80db35e"
down_revision: Union[str, None] = "4111d96afe4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("storage_key", sa.String(length=1024), nullable=True)
    )
    op.drop_column("images", "url")
    op.add_column(
        "meshes", sa.Column("storage_key", sa.String(length=1024), nullable=True)
    )
    op.add_column("meshes", sa.Column("status", sa.String(length=32), nullable=False))
    op.add_column(
        "meshes",
        sa.Column("gpu_provider_response", sa.String(length=1024), nullable=True),
    )
    op.alter_column("meshes", "seed", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("meshes", "face_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("meshes", "texture", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("meshes", "url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meshes",
        sa.Column("url", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    )
    op.alter_column("meshes", "texture", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("meshes", "face_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("meshes", "seed", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("meshes", "gpu_provider_response")
    op.drop_column("meshes", "status")
    op.drop_column("meshes", "storage_key")
    op.add_column(
        "images",
        sa.Column("url", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    )
    op.drop_column("images", "storage_key")
    # ### end Alembic commands ###
