"""Changed ProjectCollection to match model format

Revision ID: ec67c2dbbfd5
Revises: e1986b7b83cc
Create Date: 2025-06-07 22:42:30.592649

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec67c2dbbfd5"
down_revision: Union[str, None] = "e1986b7b83cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_collections",
        sa.Column("active", sa.Boolean(), server_default="True", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_collections", "active")
    # ### end Alembic commands ###
