"""Collections init

Revision ID: fd87b8bab1cd
Revises: 773797b6c838
Create Date: 2025-06-03 14:50:12.506402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd87b8bab1cd'
down_revision: Union[str, None] = '773797b6c838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_collections',
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'collection_id')
    )
    op.drop_constraint('credit_transactions_user_id_fkey', 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('images_project_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('meshes_project_id_fkey', 'meshes', type_='foreignkey')
    op.create_foreign_key(None, 'meshes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('collection_id', sa.String(length=128), nullable=True))
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'collections', ['collection_id'], ['id'])
    op.drop_constraint('textures_project_id_fkey', 'textures', type_='foreignkey')
    op.create_foreign_key(None, 'textures', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'textures', type_='foreignkey')
    op.create_foreign_key('textures_project_id_fkey', 'textures', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'collection_id')
    op.drop_constraint(None, 'meshes', type_='foreignkey')
    op.create_foreign_key('meshes_project_id_fkey', 'meshes', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_project_id_fkey', 'images', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.create_foreign_key('credit_transactions_user_id_fkey', 'credit_transactions', 'users', ['user_id'], ['id'])
    op.drop_table('project_collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
